<?xml version="1.0"?>

<robot name="drawer" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:arg name="handle_gap" default="0.10"/>
    <xacro:arg name="load_cover" default="false"/>

    <xacro:property name="drawer_height" value="0.3"/>
    <xacro:property name="drawer_width" value="0.5"/>
    <xacro:property name="drawer_length" value="0.5"/>    
    <xacro:property name="drawer_mass" value="0.100"/>

    <xacro:property name="gap" value="0.005"/>
    <xacro:property name="wall_thickness" value="0.02"/>
    <xacro:property name="wall_mass" value="0.05"/>

    <xacro:property name="side_wall_height" value="${drawer_height + 2 * gap}"/>
    <xacro:property name="side_wall_length" value="${drawer_length + gap}"/>

    <xacro:property name="base_wall_width" value="${drawer_width + 2 * gap + 2 * wall_thickness}"/>
    <xacro:property name="base_wall_length" value="${drawer_length + gap}"/>

    <xacro:property name="back_wall_height" value="${side_wall_height + 2 * wall_thickness}"/>
    <xacro:property name="back_wall_length" value="${base_wall_width}"/>

    <xacro:property name="handle_gap" value="$(arg handle_gap)"/>
    <xacro:property name="handle_thickness" value="${wall_thickness}"/>
    <xacro:property name="handle_span" value="${drawer_width / 4}"/>
    <xacro:property name="mu" value="0.00"/>
    
    <material name="omni/Blue">
      <color rgba="0 0 0.8 1"/>
    </material>
    <material name="omni/Red">
      <color rgba="1 0 0 1"/>
    </material>
    <material name="omni/White">
      <color rgba="1 1 1 1"/>
    </material>
    <material name="omni/Green">
      <color rgba="0 1 0 1"/>
    </material>
    <material name="omni/Yellow">
      <color rgba="1 1 0 1"/>
    </material>
    <material name="omni/LightGrey">
      <color rgba="0.6 0.6 0.6 1"/>
    </material>
    <material name="omni/DarkGrey">
      <color rgba="0.4 0.4 0.4 1"/>
    </material>
    <material name="brown">
      <color rgba="0.87 0.81 0.76 1.0"/>
    </material>

    <!-- RVIZ Configuration -->
    <link name="base_link" />

    <joint name="base_link__drawer" type="prismatic">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <parent link="base_link"/>
      <child link="drawer"/>
      <dynamics damping="1.0" friction="1.0"/>
      <limit effort="0.1" lower="0.0" upper="0.5" velocity="10.0"/>
      <axis xyz="1 0 0"/>
    </joint>

    <link name="drawer">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="${drawer_length} ${drawer_width} ${drawer_height}"/>
        </geometry>
        <material name="brown"/> 
      </visual>
      <collision>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <box size="${drawer_length} ${drawer_width} ${drawer_height}"/>
          </geometry>
          <contact_coefficients mu="${mu}"/>
      </collision>
      <inertial>
        <!-- CENTER OF MASS -->
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${drawer_mass}"/>
        <!-- box inertia: 1/12*m(y^2+z^2), ... -->
        <inertia ixx="${1/2 * drawer_mass * (drawer_width**2 + drawer_height**2)}" ixy="0" ixz="0" iyy="${1/2 * drawer_mass * (drawer_length**2 + drawer_height**2)}" iyz="0" izz="${1/2 * drawer_mass * (drawer_length**2 + drawer_width**2)}"/>
      </inertial>
    </link>
    <gazebo reference="drawer">
      <material>Gazebo/Wood</material>
    </gazebo>

    <joint name="base_link__left_wall" type="fixed">
      <origin rpy="0 0 0" xyz="-${gap} -${ (drawer_width / 2 + wall_thickness / 2 ) + gap} 0"/>
      <parent link="base_link"/>
      <child link="left_wall"/>
    </joint>
    
    <link name="left_wall">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="${side_wall_length} ${wall_thickness} ${side_wall_height}"/>
        </geometry>
        <material name="brown"/> 
      </visual>
      <collision>
          <origin rpy="0 0 0" xyz="0 0 0.0"/>
          <geometry>
            <box size="${side_wall_length} ${wall_thickness} ${side_wall_height}"/>
          </geometry>
      </collision>
      <inertial>
        <!-- CENTER OF MASS -->
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${wall_mass}"/>
        <!-- box inertia: 1/12*m(y^2+z^2), ... -->
        <inertia ixx="${1/2 * wall_mass * (wall_thickness**2 + side_wall_height**2)}" ixy="0" ixz="0" iyy="${1/2 * wall_mass * (side_wall_length**2 + side_wall_height**2)}" iyz="0" izz="${1/2 * wall_mass * (side_wall_length**2 + wall_thickness**2)}"/>
      </inertial>
    </link>

    <joint name="base_link__right_wall" type="fixed">
      <origin rpy="0 0 0" xyz="-${gap} ${(drawer_width/2 + wall_thickness / 2 ) + gap} 0"/>
      <parent link="base_link"/>
      <child link="right_wall"/>
    </joint>

     <link name="right_wall">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="${side_wall_length} ${wall_thickness} ${side_wall_height}"/>
        </geometry>
        <material name="brown"/> 
      </visual>
      <collision>
          <origin rpy="0 0 0" xyz="0 0 0.0"/>
          <geometry>
            <box size="${side_wall_length} ${wall_thickness} ${side_wall_height}"/>
          </geometry>
      </collision>
      <inertial>
        <!-- CENTER OF MASS -->
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${wall_mass}"/>
        <!-- box inertia: 1/12*m(y^2+z^2), ... -->
        <inertia ixx="${1/2 * wall_mass * (wall_thickness**2 + side_wall_height**2)}" ixy="0" ixz="0" iyy="${1/2 * wall_mass * (side_wall_length**2 + side_wall_height**2)}" iyz="0" izz="${1/2 * wall_mass * (side_wall_length**2 + wall_thickness**2)}"/>
      </inertial>
    </link>

    <joint name="base_link__bottom_wall" type="fixed">
      <origin rpy="0 0 0" xyz="-${gap} 0 -${drawer_height / 2 + wall_thickness / 2 + gap}"/>
      <parent link="base_link"/>
      <child link="bottom_wall"/>
    </joint>

    <link name="bottom_wall">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="${base_wall_length} ${base_wall_width} ${wall_thickness}"/>
        </geometry>
        <material name="brown"/> 
      </visual>
      <collision>
          <origin rpy="0 0 0" xyz="0 0 0.0"/>
          <geometry>
            <box size="${base_wall_length} ${base_wall_width} ${wall_thickness}"/>
          </geometry>
      </collision>
      <inertial>
        <!-- CENTER OF MASS -->
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${wall_mass}"/>
        <!-- box inertia: 1/12*m(y^2+z^2), ... -->
        <inertia ixx="${1/2 * wall_mass * (wall_thickness**2 + base_wall_width**2)}" ixy="0" ixz="0" iyy="${1/2 * wall_mass * (base_wall_length**2 + wall_thickness**2)}" iyz="0" izz="${1/2 * wall_mass * (base_wall_length**2 + base_wall_width**2)}"/>
      </inertial>
    </link>


    <joint name="base_link__top_wall" type="fixed">
      <origin rpy="0 0 0" xyz="-${gap} 0 ${drawer_height / 2 + wall_thickness / 2 + gap}"/>
      <parent link="base_link"/>
      <child link="top_wall"/>
    </joint>

    <link name="top_wall">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="${base_wall_length} ${base_wall_width} ${wall_thickness}"/>
        </geometry>
        <material name="brown"/> 
      </visual>
      <collision>
          <origin rpy="0 0 0" xyz="0 0 0.0"/>
          <geometry>
            <box size="${base_wall_length} ${base_wall_width} ${wall_thickness}"/>
          </geometry>
      </collision>
      <inertial>
        <!-- CENTER OF MASS -->
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${wall_mass}"/>
        <!-- box inertia: 1/12*m(y^2+z^2), ... -->
        <inertia ixx="${1/2 * wall_mass * (wall_thickness**2 + base_wall_width**2)}" ixy="0" ixz="0" iyy="${1/2 * wall_mass * (base_wall_length**2 + wall_thickness**2)}" iyz="0" izz="${1/2 * wall_mass * (base_wall_length**2 + base_wall_width**2)}"/>
      </inertial>
    </link>

    <joint name="base_link__back_wall" type="fixed">
      <origin rpy="0 0 0" xyz="-${drawer_length / 2 + gap + wall_thickness / 2} 0 0"/>
      <parent link="base_link"/>
      <child link="back_wall"/>
    </joint>

    <link name="back_wall">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="${wall_thickness} ${back_wall_length} ${back_wall_height}"/>
        </geometry>
        <material name="brown"/> 
      </visual>
      <collision>
          <origin rpy="0 0 0" xyz="0 0 0.0"/>
          <geometry>
            <box size="${wall_thickness} ${back_wall_length} ${back_wall_height}"/>
          </geometry>
      </collision>
      <inertial>
        <!-- CENTER OF MASS -->
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${wall_mass}"/>
        <!-- box inertia: 1/12*m(y^2+z^2), ... -->
        <inertia ixx="${1/2 * wall_mass * (back_wall_length**2 + back_wall_height**2)}" ixy="0" ixz="0" iyy="${1/2 * wall_mass * (back_wall_height**2 + wall_thickness**2)}" iyz="0" izz="${1/2 * wall_mass * (back_wall_length**2 + back_wall_length**2)}"/>
      </inertial>
    </link>

    <joint name="drawer__handle_left" type="fixed">
      <origin rpy="0 0 0" xyz="${drawer_length / 2 + handle_gap / 2} -${handle_span/2 + handle_thickness/2} 0"/>
      <parent link="drawer"/>
      <child link="handle_left"/>
    </joint>

    <link name="handle_left">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="${handle_gap} ${handle_thickness} ${handle_thickness}"/>
        </geometry>
        <material name="omni/White"/>
      </visual>
      <collision>
          <origin rpy="0 0 0" xyz="0 0 0.0"/>
          <geometry>
            <box size="${handle_gap} ${handle_thickness} ${handle_thickness}"/>
          </geometry>
      </collision>
      <inertial>
        <!-- CENTER OF MASS -->
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${wall_mass}"/>
        <!-- box inertia: 1/12*m(y^2+z^2), ... -->
        <inertia ixx="${1/2 * wall_mass * (handle_thickness**2 + handle_thickness**2)}" ixy="0" ixz="0" iyy="${1/2 * wall_mass * (handle_thickness**2 + handle_gap**2)}" iyz="0" izz="${1/2 * wall_mass * (handle_thickness**2 + handle_gap**2)}"/>
      </inertial>
    </link>

    <joint name="drawer__handle_right" type="fixed">
      <origin rpy="0 0 0" xyz="${drawer_length / 2 + handle_gap / 2} ${handle_span/2 + handle_thickness/2} 0"/>
      <parent link="drawer"/>
      <child link="handle_right"/>
    </joint>

    <link name="handle_right">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="${handle_gap} ${handle_thickness} ${handle_thickness}"/>
        </geometry>
        <material name="omni/White"/>
      </visual>
      <collision>
          <origin rpy="0 0 0" xyz="0 0 0.0"/>
          <geometry>
            <box size="${handle_gap} ${handle_thickness} ${handle_thickness}"/>
          </geometry>
      </collision>
      <inertial>
        <!-- CENTER OF MASS -->
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${wall_mass}"/>
        <!-- box inertia: 1/12*m(y^2+z^2), ... -->
        <inertia ixx="${1/2 * wall_mass * (handle_thickness**2 + handle_thickness**2)}" ixy="0" ixz="0" iyy="${1/2 * wall_mass * (handle_thickness**2 + handle_gap**2)}" iyz="0" izz="${1/2 * wall_mass * (handle_thickness**2 + handle_gap**2)}"/>
      </inertial>
    </link>


    <joint name="drawer__handle_grip" type="fixed">
      <origin rpy="0 0 0" xyz="${drawer_length / 2 + handle_gap + handle_thickness / 2} 0 0"/>
      <parent link="drawer"/>
      <child link="handle_grip"/>
    </joint>

    <link name="handle_grip">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="${handle_thickness} ${handle_span + 2 * handle_thickness} ${handle_thickness}"/>
        </geometry>
        <material name="omni/White"/>
      </visual>
      <collision>
          <origin rpy="0 0 0" xyz="0 0 0.0"/>
          <geometry>
            <box size="${handle_thickness} ${handle_span + 2 * handle_thickness} ${handle_thickness}"/>
          </geometry>
      </collision>

      <inertial>
        <!-- CENTER OF MASS -->
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${wall_mass}"/>
        <!-- box inertia: 1/12*m(y^2+z^2), ... -->
        <inertia ixx="${1/2 * wall_mass * (handle_thickness**2 + (handle_span + 2 * handle_thickness)**2)}" ixy="0" ixz="0" iyy="${1/2 * wall_mass * (handle_thickness**2 + handle_thickness**2)}" iyz="0" izz="${1/2 * wall_mass * (handle_thickness**2 + (handle_span + 2 * handle_thickness)**2)}"/>
      </inertial>
    </link>


  <xacro:if value="$(arg load_cover)">
    <link name="handle_top_cover">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="${handle_gap + handle_thickness} ${handle_span + 2 * handle_thickness} ${handle_thickness*0.3}"/>
        </geometry>
        <material name="omni/White"/>
      </visual>
      <collision>
          <origin rpy="0 0 0" xyz="0 0 0.0"/>
          <geometry>
            <box size="${handle_gap + handle_thickness} ${handle_span + 2 * handle_thickness} ${handle_thickness*0.3}"/>
          </geometry>
          <contact_coefficients mu="${mu}"/>
      </collision>

      <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${wall_mass}"/>
        <inertia ixx="${1/2 * wall_mass * (handle_thickness**2 + (handle_span + 2 * handle_thickness)**2)}" ixy="0" ixz="0" iyy="${1/2 * wall_mass * (handle_gap**2 + handle_thickness**2)}" iyz="0" izz="${1/2 * wall_mass * (handle_gap**2 + (handle_span + 2 * handle_thickness)**2)}"/>
      </inertial>
    </link>

    <joint name="d_2_htc" type="fixed">
      <origin rpy="0 0 0" xyz="${drawer_length / 2 + handle_gap/2 + handle_thickness/2} 0 ${-handle_thickness*0.3/2 - 2 * handle_thickness }"/>
      <parent link="drawer"/>
      <child link="handle_top_cover"/>
    </joint>

    <link name="handle_bottom_cover">
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <box size="${handle_thickness*0.3} ${handle_span + 2 * handle_thickness} ${(handle_gap + handle_thickness)*1.4142}"/>
          </geometry>
          <material name="omni/White"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.0"/>
            <geometry>
              <box size="${handle_thickness*0.3} ${handle_span + 2 * handle_thickness} ${(2*handle_thickness)*1.4142}"/>
            </geometry>
            <contact_coefficients mu="${mu}"/>
        </collision>

        <inertial>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <mass value="${wall_mass}"/>
          <inertia ixx="${1/2 * wall_mass * (handle_thickness**2 + (handle_span + 2 * handle_thickness)**2)}" ixy="0" ixz="0" iyy="${1/2 * wall_mass * (handle_gap**2 + handle_thickness**2)}" iyz="0" izz="${1/2 * wall_mass * (handle_gap**2 + (handle_span + 2 * handle_thickness)**2)}"/>
        </inertial>
      </link>

    <joint name="d_2_hbc" type="fixed">
      <origin rpy="0 0.78539816339 0" xyz="${-handle_thickness*0.1/2} 0 ${-(handle_gap + handle_thickness)/2}"/>
      <parent link="handle_top_cover"/>
      <child link="handle_bottom_cover"/>
    </joint>
  </xacro:if>

</robot>