optimized_gmm_name: "models/optimizer/optimized.npy"

bohb:
  min_budget: 1
  max_budget: 20
  n_iterations: 10
  run_id: 'peg_gmm'
  nameserver: '127.0.0.1'

worker:
  gmm_name: "models/GMM/gmm_peg_v2_pose_3.mat"
  env:
    show_gui: False
    with_force: False
    with_joint: False
    relative: True
    with_noise: False
    reward_type: "shaped"
    dt: 0.05
  validation:
    max_steps: 600
    render: False