gmm_name: "gmm_peg_v2_pose_5.mat"

train:
  num_random_seeds: 5
  env:
    show_gui: False
    with_force: &force False
    with_joint: &joint False
    relative: &relative True
    with_noise: &noise False
    reward_type: &reward "shaped_2"
    dt: &dt 0.01
  run:
    num_episodes: 1000
    max_steps: &steps 500
    log: True
    eval_every: 10
    eval_episodes: 10
    render: False
    save_dir: "models/"
    save_every: 10
    early_stopping: False

test:
  env:
    show_gui: True
    with_force: *force
    with_joint: *joint
    relative: *relative
    with_noise: *noise
    reward_type: *reward
    dt: *dt
  run:
    max_steps: *steps
    num_episodes: 5
    render: False

sac_agent:
  batch_size: 256
  gamma: 0.99 
  tau: 0.005 
  actor_lr: 3e-4 
  critic_lr: 3e-4 
  alpha_lr: 3e-4
  hidden_dim: 256
  window_size: 32

