train:
  num_random_seeds: 5
  env:
    show_gui: False
    with_force: &force True
    with_joint: &joint False
    relative: &relative True
    with_noise: &noise False
    reward_type: &reward "shaped_2"
    dt: &dt 0.005
    max_episode_steps: &steps 500
  run:
    num_episodes: 250
    exploration_episodes: 0
    log: True
    eval_every: 10
    save_dir: "models"
    save_every: 10
    render: False

test:
    env:
      show_gui: True
      with_force: *force
      with_joint: *joint
      relative: *relative
      with_noise: *noise
      reward_type: *reward
      dt: *dt
      max_episode_steps: *steps
    run:
      num_episodes: 5
      render: False

agent:
  batch_size: 256
  gamma: 0.99 
  tau: 0.005 
  actor_lr: 3e-4 
  critic_lr: 3e-4 
  alpha_lr: 3e-4
  hidden_dim: 256
  # actor_lr: 1.3234384129331161e-05
  # alpha_lr: 0.0006073219817739003
  # batch_size: 147
  # critic_lr: 0.003390529134067778
  # gamma: 0.9903290703518577
  # hidden_dim: 397
  # tau: 0.01167947724800859