train:
  env:
    show_gui: False
    withForce: True
    withJoint: False
    relative: True
    noise: False
    sparse: False
    dt: 0.005
  run:
    num_episodes: 1000
    max_steps: 2000
    exploration_episodes: 0
    log: True
    eval_every: 10
    render: False
    save_dir: "models/SAC_models"
    save_filename: "peg"
    save_every: 10

test:
    env:
      show_gui: True
      withForce: True
      withJoint: False
      relative: True
      noise: False
      sparse: False
      dt: 0.005
    run:
      max_steps: 2000
      num_episodes: 5
      render: False

agent:
  # actor_lr: 1.3e-06 
  # alpha_lr: 5.3e-06
  # batch_size: 160
  # critic_lr: 2.0e-06
  # hidden_dim: 400 
  # tau: 0.016
  batch_size: 256
  gamma: 0.99 
  tau: 0.005 
  actor_lr: 3e-4 
  critic_lr: 3e-4 
  alpha_lr: 3e-4
  hidden_dim: 256