bohb:
  min_budget: 400
  max_budget: 500
  n_iterations: 4
  run_id: 'peg'
  nameserver: '127.0.0.1'

worker:
  gmm_name: "models/GMM_models/gmm_peg_v2_pose_9.npy"
  env:
    show_gui: False
    with_force: False
    with_joint: False
    relative: True
    with_noise: False
    sparse: False
    dt: 0.05
  train:
    max_steps: 600
    log: True
    eval_every: 10
    eval_episodes: 5
    render: False
    save_filename: "peg"
    save_every: 10
  validation:
    max_steps: 1000
    num_episodes: 10
    render: False