bohb:
  min_budget: 100
  max_budget: 300
  n_iterations: 5
  run_id: 'peg'
  nameserver: '127.0.0.1'

worker:
  env:
    show_gui: False
    with_force: False
    with_joint: False
    relative: True
    with_noise: False
    reward_type: "shaped_2"
    dt: 0.005
    max_episode_steps: 500
  train:
    exploration_episodes: 0
    log: True
    eval_every: 10
    eval_episodes: 5
    render: False
    save_every: 10
  validation:
    num_episodes: 10
    render: False