train:
  env:
    show_gui: False
    with_force: False
    with_joint: False
    relative: True
    with_noise: False
    sparse: False
    dt: 0.005
  run:
    num_episodes: 2000
    max_steps: 1000
    exploration_episodes: 0
    log: True
    eval_every: 10
    render: False
    save_dir: "models/SAC_models"
    save_filename: "peg"
    save_every: 10

test:
    env:
      show_gui: True
      with_force: False
      with_joint: False
      relative: True
      with_noise: False
      sparse: False
      dt: 0.005
    run:
      max_steps: 1000
      num_episodes: 5
      render: False

agent:
  batch_size: 256
  gamma: 0.99 
  tau: 0.005 
  actor_lr: 3e-4 
  critic_lr: 3e-4 
  alpha_lr: 3e-4
  hidden_dim: 256

  # actor_lr: 6.1e-4
  # alpha_lr: 1.39e-06
  # batch_size: 175
  # critic_lr: 1.88e-4
  # hidden_dim: 360 
  # tau: 9.5e-3